# Generated by Django 6.0.6 on 2026-07-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('vacancy', models.IntegerField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateField()),
                ('hr_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hr_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('hr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('job_type', models.CharField(max_length=100)),
                ('experience', models.FloatField()),
                ('company_location', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Jobs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
